package game_engine.figures;

public enum FigureType {

	PENETRATING_WHOLE_1,
	PENETRATING_WHOLE_2,
	PENETRATING_WHOLE_3,
	PENETRATING_WHOLE_4,
	PENETRATING_WHOLE_5,
	PENETRATING_WHOLE_6,
	PENETRATING_WHOLE_7,
	PENETRATING_WHOLE_8,
	PENETRATING_WHOLE_9,
	WHOLE_1,
	WHOLE_2,
	WHOLE_3,
	WHOLE_4,
	WHOLE_5,
	WHOLE_6,
	WHOLE_7,
	WHOLE_8,
	WHOLE_9,
//	WHOLE_10,
//	WHOLE_11,
//	WHOLE_12,
//	WHOLE_MORE,
	PENETRATING_SEMIWHOLE_2,
	PENETRATING_SEMIWHOLE_3,
	SEMIWHOLE_2,
	SEMIWHOLE_3,
	SEPARATE_2_2,
	SEPARATE_2_3,
	SEPARATE_3_3,
//	SEPARATE_3,
//	SEPARATE_4, 
	;
	public static final int WHOLE_MAX_BRICKS = 9;
}
